### ISSUE TITLE
unknown enum constant Scope.LIBRARY_GROUP	

### ISSUE THREAD

**Issue by BarejaHemant** [nyris/Camera.Android#1]
I have updated the nyris camera lib to 1.0.1 and got gradle sync issue:

unknown enum constant Scope.LIBRARY_GROUP |  

Which library version should be downgrade or upgrade?

**Comment by smellouk** [comment]
Hi, 

I think the issue is related to `support-annotation`, we are using recent version. To fix the issue : you can update your support libraries  or you can also exclude `support library` from `camera library`.
